version: '3'
services:
  fastapi:
    build:
      context: ./api/
      dockerfile: fastapi.Dockerfile
    tty: true
    restart: unless-stopped
    ports:
      - "7000:8000"
    # volumes:
    #   - .api/volume:/code/volume  
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]

  postgres:
    container_name: postgres_AM
    image: postgres
    restart: always
    volumes:
      - ./bdd/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
      
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "15432:80"