version: '3'
services:
  fastapi:
    container_name: fastapi_AM
    build:
      context: ./api/
      dockerfile: fastapi.Dockerfile
    tty: true
    restart: unless-stopped
    ports:
      - "7000:8000"
    # volumes:
    #   - .api/volume:/code/volume  
    networks:
      - app-network
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]

  postgres:
    container_name: postgres_AM
    image: postgres
    restart: always
    volumes:
      - ./bdd/db-data/:/var/lib/postgresql/data
      - ./bdd/sql:/bdd/
    env_file:
      - .env  
    ports:
      - "5432:5432"
    networks:
      - app-network
      
  pgadmin:
    container_name: pgadmin4_AM-DO-NOT-KEEP-IN-PRODUCTION
    image: dpage/pgadmin4
    restart: always
    env_file:
      - .env
    ports:
      - "15432:80"
    networks:
        - app-network

networks:
    app-network:
        driver: bridge
