# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.27.0
import dataclasses
import decimal


@dataclasses.dataclass()
class CoordsGp:
    producer_id: int
    uid: int
    latitude: decimal.Decimal
    longitude: decimal.Decimal


@dataclasses.dataclass()
class Producer:
    id: int
    name: str
